export const selectTypes = state => state.enum.enums.types;
export const selectBowl_types = state => state.enum.enums.bowl_types;
export const selectBrands = state => state.enum.enums.brands;
export const selectColors = state => state.enum.enums.colors;
export const selectFlavors = state => state.enum.enums.flavors;
export const selectHookah_size = state => state.enum.enums.hookah_size;
export const selectPromotions = state => state.enum.enums.promotions;
export const selectError = state => state.enum.error;
export const selectIsLoading = state => state.enum.isLoading;
